baseURL = "https://abudlightlime.com"
title = "Home"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "black-and-light"
preserveTaxonomyNames = true

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "The Bud Light Lime Blog"
  disableWebFonts = false

[[menu.main]]
    name = "CV"
    url  = "https://docs.google.com/document/d/1L_NP2sQIvnh4hndU-JbhczP-uAUPY5ie1_vsmrOdz_A"
[[menu.main]]
    name = "Github"
    url  = "https://github.com/angles-n-daemons"
[[menu.main]]
    name = "LinkedIn"
    url  = "https://www.linkedin.com/in/brian-dillmann-0a997979/"
