baseURL = "https://abudlightlime.com"
title = "Home"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "black-and-light"
preserveTaxonomyNames = true

pygmentsUseClassic = false
pygmentsCodeFences = true

[params]
  sitename = "The Bud Light Lime Blog"
  disableWebFonts = false

[[menu.main]]
    name = "Resume"
    url  = "https://docs.google.com/document/d/1jkPJ6dlcMnNd-sNn2veAx8Qzf7CQFBuAtXS1_ZSWjig/edit"
[[menu.main]]
    name = "Github"
    url  = "https://github.com/angles-n-daemons"
[[menu.main]]
    name = "LinkedIn"
    url  = "https://www.linkedin.com/in/brian-dillmann-0a997979/"
